language: cpp

notifications:
  email: false

addons:
  apt:
    packages:
      - libssl-dev
      - python-dev
      - python3-pip
      - scons
      - swig

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang
    # - os: linux
    #   compiler: gcc
    #   dist: trusty
    #   env:
    #     py3: true
    # - os: osx
    #   compiler: clang
    #   env:
    #     py3: true

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install swig
    brew outdated openssl || brew upgrade openssl
    brew outdated cmake || brew upgrade cmake
  fi
- python -V

script:
- git submodule update --init --recursive
- cd tests/s2-geometry && ./travis.sh && cd -
# dependencies for Python tests
- pip install --user --upgrade pip
- pip install --user numpy
- "pip install --user .[tests]"
- nosetests-2.7 -vv
# py3
- pip3 install --user --upgrade pip
- pip3 install --user numpy
- "pip3 install --user .[tests]"
- nosetests-3.4 -vv --exclude=compare_implementations_test
